// Objective-C API for talking to github.com/gnolang/gnonative/framework/service Go package.
//   gobind -lang=objc -prefix="Gno" github.com/gnolang/gnonative/framework/service
//
// File is generated by gobind. Do not edit.

#ifndef __GnoGnonative_H__
#define __GnoGnonative_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class GnoGnonativeBridge;
@class GnoGnonativeBridgeConfig;
@protocol GnoGnonativePromiseBlock;
@class GnoGnonativePromiseBlock;

@protocol GnoGnonativePromiseBlock <NSObject>
- (void)callReject:(NSError* _Nullable)error;
- (void)callResolve:(NSString* _Nullable)reply;
@end

@interface GnoGnonativeBridge : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nullable instancetype)init:(GnoGnonativeBridgeConfig* _Nullable)config;
- (BOOL)close:(NSError* _Nullable* _Nullable)error;
- (NSString* _Nonnull)getTcpAddr;
- (long)getTcpPort;
- (NSString* _Nonnull)getUDSPath;
@end

@interface GnoGnonativeBridgeConfig : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nullable instancetype)init;
@property (nonatomic) NSString* _Nonnull rootDir;
@property (nonatomic) NSString* _Nonnull tmpDir;
@property (nonatomic) BOOL useTcpListener;
@property (nonatomic) BOOL disableUdsListener;
@end

FOUNDATION_EXPORT GnoGnonativeBridge* _Nullable GnoGnonativeNewBridge(GnoGnonativeBridgeConfig* _Nullable config, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT GnoGnonativeBridgeConfig* _Nullable GnoGnonativeNewBridgeConfig(void);

@class GnoGnonativePromiseBlock;

@interface GnoGnonativePromiseBlock : NSObject <goSeqRefInterface, GnoGnonativePromiseBlock> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)callReject:(NSError* _Nullable)error;
- (void)callResolve:(NSString* _Nullable)reply;
@end

#endif
