
// Objective-C API for talking to the following Go packages
//
//	github.com/gnolang/gnonative/framework/service
//
// File is generated by gomobile bind. Do not edit.
#ifndef __GnoCore_FRAMEWORK_H__
#define __GnoCore_FRAMEWORK_H__

#include "GnoGnonative.objc.h"
#include "Universe.objc.h"

#endif
