// Objective-C API for talking to github.com/gnolang/gnonative/framework/service Go package.
//   gobind -lang=objc -prefix="Gno" github.com/gnolang/gnonative/framework/service
//
// File is generated by gobind. Do not edit.

#ifndef __GnoGnonative_H__
#define __GnoGnonative_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class GnoGnonativeBridge;
@class GnoGnonativeBridgeConfig;
@protocol GnoGnonativePromiseBlock;
@class GnoGnonativePromiseBlock;
@protocol GnoGnonativeServiceClient;
@class GnoGnonativeServiceClient;

@protocol GnoGnonativePromiseBlock <NSObject>
- (void)callReject:(NSError* _Nullable)error;
- (void)callResolve:(NSString* _Nullable)reply;
@end

@protocol GnoGnonativeServiceClient <NSObject>
- (void)closeStreamClientWithPromiseBlock:(id<GnoGnonativePromiseBlock> _Nullable)promise id_:(NSString* _Nullable)id_;
- (void)createStreamClientWithPromiseBlock:(id<GnoGnonativePromiseBlock> _Nullable)promise method:(NSString* _Nullable)method jsonMessage:(NSString* _Nullable)jsonMessage;
- (void)invokeGrpcMethodWithPromiseBlock:(id<GnoGnonativePromiseBlock> _Nullable)promise method:(NSString* _Nullable)method jsonMessage:(NSString* _Nullable)jsonMessage;
- (void)streamClientReceiveWithPromiseBlock:(id<GnoGnonativePromiseBlock> _Nullable)promise id_:(NSString* _Nullable)id_;
@end

@interface GnoGnonativeBridge : NSObject <goSeqRefInterface, GnoGnonativeServiceClient> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nullable instancetype)init:(GnoGnonativeBridgeConfig* _Nullable)config;
@property (nonatomic) id<GnoGnonativeServiceClient> _Nullable serviceClient;
- (BOOL)close:(NSError* _Nullable* _Nullable)error;
- (void)closeStreamClientWithPromiseBlock:(id<GnoGnonativePromiseBlock> _Nullable)promise id_:(NSString* _Nullable)id_;
- (void)createStreamClientWithPromiseBlock:(id<GnoGnonativePromiseBlock> _Nullable)promise method:(NSString* _Nullable)method jsonMessage:(NSString* _Nullable)jsonMessage;
- (NSString* _Nonnull)getTcpAddr;
- (long)getTcpPort;
- (NSString* _Nonnull)getUDSPath;
- (void)invokeGrpcMethodWithPromiseBlock:(id<GnoGnonativePromiseBlock> _Nullable)promise method:(NSString* _Nullable)method jsonMessage:(NSString* _Nullable)jsonMessage;
- (void)streamClientReceiveWithPromiseBlock:(id<GnoGnonativePromiseBlock> _Nullable)promise id_:(NSString* _Nullable)id_;
@end

@interface GnoGnonativeBridgeConfig : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nullable instancetype)init;
@property (nonatomic) NSString* _Nonnull rootDir;
@property (nonatomic) NSString* _Nonnull tmpDir;
@property (nonatomic) BOOL useTcpListener;
@property (nonatomic) BOOL disableUdsListener;
@end

FOUNDATION_EXPORT GnoGnonativeBridge* _Nullable GnoGnonativeNewBridge(GnoGnonativeBridgeConfig* _Nullable config, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT GnoGnonativeBridgeConfig* _Nullable GnoGnonativeNewBridgeConfig(void);

// skipped function NewServiceClient with unsupported parameter or return types


@class GnoGnonativePromiseBlock;

@class GnoGnonativeServiceClient;

@interface GnoGnonativePromiseBlock : NSObject <goSeqRefInterface, GnoGnonativePromiseBlock> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)callReject:(NSError* _Nullable)error;
- (void)callResolve:(NSString* _Nullable)reply;
@end

@interface GnoGnonativeServiceClient : NSObject <goSeqRefInterface, GnoGnonativeServiceClient> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)closeStreamClientWithPromiseBlock:(id<GnoGnonativePromiseBlock> _Nullable)promise id_:(NSString* _Nullable)id_;
- (void)createStreamClientWithPromiseBlock:(id<GnoGnonativePromiseBlock> _Nullable)promise method:(NSString* _Nullable)method jsonMessage:(NSString* _Nullable)jsonMessage;
- (void)invokeGrpcMethodWithPromiseBlock:(id<GnoGnonativePromiseBlock> _Nullable)promise method:(NSString* _Nullable)method jsonMessage:(NSString* _Nullable)jsonMessage;
- (void)streamClientReceiveWithPromiseBlock:(id<GnoGnonativePromiseBlock> _Nullable)promise id_:(NSString* _Nullable)id_;
@end

#endif
